export const VOICE_TRAINING_TEXTS = [
  "The quick brown fox jumps over the lazy dog near the riverbank.",
  "Technology has revolutionized how we communicate with each other daily.",
  "Beautiful sunsets paint the sky with vibrant colors every evening.",
  "Coffee shops buzz with conversations and the aroma of fresh beans.",
  "Mountains stand tall against the horizon, covered in morning mist.",
  "Children laugh and play in the park during warm summer afternoons.",
  "Books transport us to different worlds through imagination and storytelling.",
  "Ocean waves crash rhythmically against the sandy shore below.",
  "Music has the power to evoke deep emotions and cherished memories.",
  "Gardens bloom with colorful flowers throughout the changing seasons.",
  "Friendship requires trust, understanding, and genuine care for others.",
  "Innovation drives progress in science, medicine, and technology fields.",
  "Cooking brings families together around the dinner table each night.",
  "Travel opens our minds to new cultures and different perspectives.",
  "Exercise keeps our bodies healthy and our minds sharp and focused.",
  "Art expresses creativity through various mediums and artistic techniques.",
  "Education empowers individuals to achieve their dreams and aspirations.",
  "Weather patterns change dramatically throughout the year in many regions.",
  "Photography captures precious moments that we treasure for a lifetime.",
  "Architecture combines functionality with aesthetic beauty in building design.",
  "Sports teach teamwork, discipline, and the importance of perseverance.",
  "Nature provides peace and tranquility away from busy city life.",
  "History teaches us valuable lessons about human civilization and progress.",
  "Science explores the mysteries of our universe through careful observation.",
  "Literature reflects the human experience across different cultures and times.",
  "Dancing expresses joy and emotion through graceful movement and rhythm.",
  "Gardening connects us with nature and provides fresh, healthy food.",
  "Volunteering helps communities and gives us a sense of purpose.",
  "Learning new languages opens doors to different cultures and opportunities.",
  "Meditation brings inner peace and clarity to our busy, stressful lives.",
  "Entrepreneurship requires creativity, risk-taking, and persistent determination.",
  "Family traditions create lasting bonds and cherished childhood memories.",
  "Environmental conservation protects our planet for future generations to enjoy.",
  "Public speaking builds confidence and improves communication skills significantly.",
  "Healthy relationships require open communication, respect, and mutual understanding.",
  "Time management helps us balance work, family, and personal interests effectively.",
  "Creative writing allows us to express thoughts and emotions through storytelling.",
  "Problem-solving skills are essential in both professional and personal situations.",
  "Cultural diversity enriches our communities with different traditions and perspectives.",
  "Lifelong learning keeps our minds active and helps us adapt to change."
]; 