apiVersion: v2
name: sus-nexus-fhir
description: SUS Nexus — FHIR R4 Gateway (Quarkus)
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/sus-nexus/sus-nexus
keywords: [sus-nexus, fhir, r4, quarkus]
maintainers:
  - name: Plataforma SUS Nexus
annotations:
  sus-nexus.gov.br/component: fhir-gateway
