quarkus.application.name=connector-example
quarkus.http.port=8099
quarkus.banner.enabled=false
quarkus.log.console.filter=pii-mask
connector.tenant-id=${TENANT_ID:ibge_3143302}
quarkus.rest-client.core.url=${CORE_URL:http://localhost:8080}
connector.core.auth.mode=${CORE_AUTH_MODE:static}
connector.core.auth.static-token=${CORE_STATIC_TOKEN:dev-token}
quarkus.oidc-client.enabled=false
connector.raw-store.dir=${RAW_STORE_DIR:data/raw-zone}
connector.dlq.dir=${DLQ_DIR:data/dlq}
example.input-dir=${EXAMPLE_INPUT_DIR:data/example/in}
%test.quarkus.http.test-port=0
%test.example.input-dir=target/test-input/example
%test.connector.raw-store.dir=target/test-raw-zone
%test.connector.dlq.dir=target/test-dlq
